parameters:
  name: ''
  pool: ''

variables:
  CPPTOOL_VERSION: v0.14.6-insiders
  CPPTOOLS_DEV: 1

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - powershell: |
      # Download debugAdapters from an existing extension version. See settings to set CPPTOOL_VERSION
      mkdir -p %UserProfile%\.vscode\extensions\ms-vscode.cpptools-$CPPTOOL_VERSION
      Invoke-WebRequest -Uri https://github.com/Microsoft/vscode-cpptools/releases/download/$CPPTOOL_VERSION/cpptools.vsix -OutFile %UserProfile%\cpptools.vsix
      Expand-Archive %UserProfile%\cpptools.vsix -DestinationPath %UserProfile%\cpptools
      Move-Item %UserProfile%\extension\debugAdapters %UserProfile%\.vscode\extensions\ms-vscode.cpptools-$CPPTOOL_VERSION\debugAdapters
    displayName: 'Download Debugger Dependencies'

  - task: NodeTool@0
    displayName: Use Node 8.x'
    inputs:
      versionSpec: 8.x

  - script: npm install
    displayName: "Install Dependencies"
    workingDirectory: '$(Build.SourcesDirectory)/Extension'
      
  - script: npm run compile
    displayName: "Compile Sources"
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: npm run pr-check
    displayName: 'Validate Extension/package.json'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: npm run tslint
    displayName: 'Run Linter'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: npm run unitTests
    displayName: 'Run Unit Tests'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: npm run integrationTests
    displayName: 'Run Integration Tests'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'