parameters:
  name: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - task: NodeTool@0
    displayName: Use Node 8.x'
    inputs:
      versionSpec: 8.x
  - script: npm install
    workingDirectory: 'Extension'
  - script: npm run pr-check
    workingDirectory: 'Extension'
  - script: npm run tslint
    workingDirectory: 'Extension'
  - script: npm run compile
    workingDirectory: 'Extension'
  - script: npm run test
    workingDirectory: 'Extension'